# Generated by Django 5.0.6 on 2024-05-16 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, null=True)),
                ('price', models.CharField(max_length=225, null=True)),
                ('description', models.TextField(null=True)),
                ('images', models.ImageField(null=True, upload_to='fruit/')),
            ],
        ),
        migrations.CreateModel(
            name='CheckoutAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=225, null=True, verbose_name='First name')),
                ('last_name', models.CharField(max_length=225, null=True, verbose_name='Last name')),
                ('contact', models.CharField(max_length=11, null=True, verbose_name='Contact no')),
                ('email', models.CharField(max_length=225, null=True, verbose_name='Email address')),
                ('address', models.CharField(max_length=225, null=True, verbose_name='User address')),
                ('country', models.CharField(blank=True, max_length=225, null=True)),
                ('city', models.CharField(blank=True, max_length=225, null=True)),
                ('state', models.CharField(max_length=225, null=True, verbose_name='state name')),
                ('zip_code', models.CharField(max_length=10, null=True, verbose_name='Zip code')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('total', models.CharField(max_length=225, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productdetail')),
            ],
        ),
    ]
