# Generated by Django 5.0.6 on 2024-05-16 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name', max_length=225, null=True, verbose_name='Name')),
                ('email', models.EmailField(help_text='Enter email', max_length=225, null=True, verbose_name='Email')),
                ('phone', models.CharField(help_text='Contact no', max_length=225, null=True, verbose_name='Contact no')),
                ('subject', models.CharField(help_text='Customer queries', max_length=225, null=True, verbose_name='Subject')),
                ('message', models.TextField(help_text='Enter message', max_length=225, null=True, verbose_name='Message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact Us',
                'verbose_name_plural': 'Contact Us',
            },
        ),
    ]
